language: java
sudo: false
cache:
  directories:
  - $HOME/.m2
addons:
  hosts:
    - test-bucket.localhost
env:
  matrix:
    - SUITE=unit
    - SUITE=integration
  global:
    - PATH=$PATH:$HOME/.s3cmd
    - SECOR_LOCAL_S3=true
    - S3CMD=1.0.1
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
before_install:
  - wget https://github.com/s3tools/s3cmd/archive/v$S3CMD.tar.gz -O /tmp/s3cmd.tar.gz
  - tar -xzf /tmp/s3cmd.tar.gz -C $HOME
  - mv $HOME/s3cmd-$S3CMD $HOME/.s3cmd
  - cd $HOME/.s3cmd && python setup.py install --user && cd -
  - gem install fakes3 -v 0.1.7
install: make build
script:
  - make $SUITE
matrix:
  fast_finish: true
